// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

class NativeLibrary {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NativeLibrary(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NativeLibrary.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// \brief
  /// Construct a new error.
  ffi.Pointer<Error> rune_error_new(
    ffi.Pointer<ffi.Int8> msg,
  ) {
    return _rune_error_new(
      msg,
    );
  }

  late final _rune_error_new_ptr =
      _lookup<ffi.NativeFunction<_c_rune_error_new>>('rune_error_new');
  late final _dart_rune_error_new _rune_error_new =
      _rune_error_new_ptr.asFunction<_dart_rune_error_new>();

  /// \brief
  /// Free the error once you are done with it.
  void rune_error_free(
    ffi.Pointer<Error> e,
  ) {
    return _rune_error_free(
      e,
    );
  }

  late final _rune_error_free_ptr =
      _lookup<ffi.NativeFunction<_c_rune_error_free>>('rune_error_free');
  late final _dart_rune_error_free _rune_error_free =
      _rune_error_free_ptr.asFunction<_dart_rune_error_free>();

  /// \brief
  /// Return a newly allocated string containing the error's backtrace.
  ffi.Pointer<ffi.Int8> rune_error_backtrace(
    ffi.Pointer<Error> error,
  ) {
    return _rune_error_backtrace(
      error,
    );
  }

  late final _rune_error_backtrace_ptr =
      _lookup<ffi.NativeFunction<_c_rune_error_backtrace>>(
          'rune_error_backtrace');
  late final _dart_rune_error_backtrace _rune_error_backtrace =
      _rune_error_backtrace_ptr.asFunction<_dart_rune_error_backtrace>();

  /// \brief
  /// Return a newly allocated string describing the error.
  ffi.Pointer<ffi.Int8> rune_error_to_string(
    ffi.Pointer<Error> error,
  ) {
    return _rune_error_to_string(
      error,
    );
  }

  late final _rune_error_to_string_ptr =
      _lookup<ffi.NativeFunction<_c_rune_error_to_string>>(
          'rune_error_to_string');
  late final _dart_rune_error_to_string _rune_error_to_string =
      _rune_error_to_string_ptr.asFunction<_dart_rune_error_to_string>();

  /// \brief
  /// Return a newly allocated string describing the error and any errors that
  /// may have caused it.
  ///
  /// This will also contain a backtrace if the `RUST_BACKTRACE` environment
  /// variable is set.
  ffi.Pointer<ffi.Int8> rune_error_to_string_verbose(
    ffi.Pointer<Error> error,
  ) {
    return _rune_error_to_string_verbose(
      error,
    );
  }

  late final _rune_error_to_string_verbose_ptr =
      _lookup<ffi.NativeFunction<_c_rune_error_to_string_verbose>>(
          'rune_error_to_string_verbose');
  late final _dart_rune_error_to_string_verbose _rune_error_to_string_verbose =
      _rune_error_to_string_verbose_ptr
          .asFunction<_dart_rune_error_to_string_verbose>();

  /// \brief
  /// Free a `WasmerRuntime` once you are done with it.
  void rune_wasmer_runtime_free(
    ffi.Pointer<WasmerRuntime> runtime,
  ) {
    return _rune_wasmer_runtime_free(
      runtime,
    );
  }

  late final _rune_wasmer_runtime_free_ptr =
      _lookup<ffi.NativeFunction<_c_rune_wasmer_runtime_free>>(
          'rune_wasmer_runtime_free');
  late final _dart_rune_wasmer_runtime_free _rune_wasmer_runtime_free =
      _rune_wasmer_runtime_free_ptr
          .asFunction<_dart_rune_wasmer_runtime_free>();

  ffi.Pointer<RunicosBaseImage> rune_image_new() {
    return _rune_image_new();
  }

  late final _rune_image_new_ptr =
      _lookup<ffi.NativeFunction<_c_rune_image_new>>('rune_image_new');
  late final _dart_rune_image_new _rune_image_new =
      _rune_image_new_ptr.asFunction<_dart_rune_image_new>();

  void rune_image_free(
    ffi.Pointer<RunicosBaseImage> image,
  ) {
    return _rune_image_free(
      image,
    );
  }

  late final _rune_image_free_ptr =
      _lookup<ffi.NativeFunction<_c_rune_image_free>>('rune_image_free');
  late final _dart_rune_image_free _rune_image_free =
      _rune_image_free_ptr.asFunction<_dart_rune_image_free>();
}

class Error extends ffi.Opaque {}

class __darwin_pthread_handler_rec extends ffi.Struct {
  external ffi.Pointer<ffi.NativeFunction<_typedefC_1>> __routine;

  external ffi.Pointer<ffi.Void> __arg;

  external ffi.Pointer<__darwin_pthread_handler_rec> __next;
}

class _opaque_pthread_attr_t extends ffi.Struct {
  @ffi.Int64()
  external int __sig;

  @ffi.Array.multi([56])
  external ffi.Array<ffi.Int8> __opaque;
}

class _opaque_pthread_cond_t extends ffi.Struct {
  @ffi.Int64()
  external int __sig;

  @ffi.Array.multi([40])
  external ffi.Array<ffi.Int8> __opaque;
}

class _opaque_pthread_condattr_t extends ffi.Struct {
  @ffi.Int64()
  external int __sig;

  @ffi.Array.multi([8])
  external ffi.Array<ffi.Int8> __opaque;
}

class _opaque_pthread_mutex_t extends ffi.Struct {
  @ffi.Int64()
  external int __sig;

  @ffi.Array.multi([56])
  external ffi.Array<ffi.Int8> __opaque;
}

class _opaque_pthread_mutexattr_t extends ffi.Struct {
  @ffi.Int64()
  external int __sig;

  @ffi.Array.multi([8])
  external ffi.Array<ffi.Int8> __opaque;
}

class _opaque_pthread_once_t extends ffi.Struct {
  @ffi.Int64()
  external int __sig;

  @ffi.Array.multi([8])
  external ffi.Array<ffi.Int8> __opaque;
}

class _opaque_pthread_rwlock_t extends ffi.Struct {
  @ffi.Int64()
  external int __sig;

  @ffi.Array.multi([192])
  external ffi.Array<ffi.Int8> __opaque;
}

class _opaque_pthread_rwlockattr_t extends ffi.Struct {
  @ffi.Int64()
  external int __sig;

  @ffi.Array.multi([16])
  external ffi.Array<ffi.Int8> __opaque;
}

class _opaque_pthread_t extends ffi.Struct {
  @ffi.Int64()
  external int __sig;

  external ffi.Pointer<__darwin_pthread_handler_rec> __cleanup_stack;

  @ffi.Array.multi([8176])
  external ffi.Array<ffi.Int8> __opaque;
}

/// \brief
/// `&'lt [T]` but with a guaranteed `#[repr(C)]` layout.
///
/// # C layout (for some given type T)
///
/// ```c
/// typedef struct {
/// // Cannot be NULL
/// T * ptr;
/// size_t len;
/// } slice_T;
/// ```
///
/// # Nullable pointer?
///
/// If you want to support the above typedef, but where the `ptr` field is
/// allowed to be `NULL` (with the contents of `len` then being undefined)
/// use the `Option< slice_ptr<_> >` type.
class slice_ref_uint8_t extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Uint64()
  external int len;
}

class RunicosBaseImage extends ffi.Opaque {}

class WasmerRuntime extends ffi.Opaque {}

class Ok_WasmerRuntime_ptr_t extends ffi.Struct {
  @ffi.Uint8()
  external int tag;

  external ffi.Pointer<WasmerRuntime> value;
}

class Err_Error_ptr_t extends ffi.Struct {
  @ffi.Uint8()
  external int tag;

  external ffi.Pointer<Error> error;
}

class Ok_uint8_t extends ffi.Struct {
  @ffi.Uint8()
  external int tag;

  @ffi.Uint8()
  external int value;
}

/// \brief
/// Like [`slice_ref`] and [`slice_mut`], but with any lifetime attached
/// whatsoever.
///
/// It is only intended to be used as the parameter of a **callback** that
/// locally borrows it, due to limitations of the [`ReprC`][
/// `trait@crate::layout::ReprC`] design _w.r.t._ higher-rank trait bounds.
///
/// # C layout (for some given type T)
///
/// ```c
/// typedef struct {
/// // Cannot be NULL
/// T * ptr;
/// size_t len;
/// } slice_T;
/// ```
///
/// # Nullable pointer?
///
/// If you want to support the above typedef, but where the `ptr` field is
/// allowed to be `NULL` (with the contents of `len` then being undefined)
/// use the `Option< slice_ptr<_> >` type.
class slice_raw_uint8_t extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Uint64()
  external int len;
}

class LogRecord_t extends ffi.Struct {
  @ffi.Uint32()
  external int level;

  external slice_raw_uint8_t target;

  external ffi.Pointer<ffi.Int8> message;
}

class BoxDynFnMut1_Result_uint8_Error_ptr_LogRecord_t extends ffi.Struct {
  external ffi.Pointer<ffi.Void> env_ptr;

  external ffi.Pointer<ffi.NativeFunction<_typedefC_2>> call;

  external ffi.Pointer<ffi.NativeFunction<_typedefC_3>> free;
}

const int RESULT_TAG_OK = 0;

const int RESULT_TAG_ERR = 1;

const int LOG_LEVEL_ERROR = 1;

const int LOG_LEVEL_WARN = 2;

const int LOG_LEVEL_INFO = 3;

const int LOG_LEVEL_DEBUG = 4;

const int LOG_LEVEL_TRACE = 5;

const int __DARWIN_ONLY_64_BIT_INO_T = 0;

const int __DARWIN_ONLY_UNIX_CONFORMANCE = 1;

const int __DARWIN_ONLY_VERS_1050 = 0;

const int __DARWIN_UNIX03 = 1;

const int __DARWIN_64_BIT_INO_T = 1;

const int __DARWIN_VERS_1050 = 1;

const int __DARWIN_NON_CANCELABLE = 0;

const String __DARWIN_SUF_64_BIT_INO_T = '\$INODE64';

const String __DARWIN_SUF_1050 = '\$1050';

const String __DARWIN_SUF_EXTSN = '\$DARWIN_EXTSN';

const int __DARWIN_C_ANSI = 4096;

const int __DARWIN_C_FULL = 900000;

const int __DARWIN_C_LEVEL = 900000;

const int __STDC_WANT_LIB_EXT1__ = 1;

const int __DARWIN_NO_LONG_LONG = 0;

const int _DARWIN_FEATURE_64_BIT_INODE = 1;

const int _DARWIN_FEATURE_ONLY_UNIX_CONFORMANCE = 1;

const int _DARWIN_FEATURE_UNIX_CONFORMANCE = 3;

const int __DARWIN_NULL = 0;

const int __PTHREAD_SIZE__ = 8176;

const int __PTHREAD_ATTR_SIZE__ = 56;

const int __PTHREAD_MUTEXATTR_SIZE__ = 8;

const int __PTHREAD_MUTEX_SIZE__ = 56;

const int __PTHREAD_CONDATTR_SIZE__ = 8;

const int __PTHREAD_COND_SIZE__ = 40;

const int __PTHREAD_ONCE_SIZE__ = 8;

const int __PTHREAD_RWLOCK_SIZE__ = 192;

const int __PTHREAD_RWLOCKATTR_SIZE__ = 16;

const int __DARWIN_WCHAR_MAX = 2147483647;

const int __DARWIN_WCHAR_MIN = -2147483648;

const int __DARWIN_WEOF = -1;

const int _FORTIFY_SOURCE = 2;

const int NULL = 0;

const int USER_ADDR_NULL = 0;

const int __WORDSIZE = 64;

const int INT8_MAX = 127;

const int INT16_MAX = 32767;

const int INT32_MAX = 2147483647;

const int INT64_MAX = 9223372036854775807;

const int INT8_MIN = -128;

const int INT16_MIN = -32768;

const int INT32_MIN = -2147483648;

const int INT64_MIN = -9223372036854775808;

const int UINT8_MAX = 255;

const int UINT16_MAX = 65535;

const int UINT32_MAX = 4294967295;

const int UINT64_MAX = -1;

const int INT_LEAST8_MIN = -128;

const int INT_LEAST16_MIN = -32768;

const int INT_LEAST32_MIN = -2147483648;

const int INT_LEAST64_MIN = -9223372036854775808;

const int INT_LEAST8_MAX = 127;

const int INT_LEAST16_MAX = 32767;

const int INT_LEAST32_MAX = 2147483647;

const int INT_LEAST64_MAX = 9223372036854775807;

const int UINT_LEAST8_MAX = 255;

const int UINT_LEAST16_MAX = 65535;

const int UINT_LEAST32_MAX = 4294967295;

const int UINT_LEAST64_MAX = -1;

const int INT_FAST8_MIN = -128;

const int INT_FAST16_MIN = -32768;

const int INT_FAST32_MIN = -2147483648;

const int INT_FAST64_MIN = -9223372036854775808;

const int INT_FAST8_MAX = 127;

const int INT_FAST16_MAX = 32767;

const int INT_FAST32_MAX = 2147483647;

const int INT_FAST64_MAX = 9223372036854775807;

const int UINT_FAST8_MAX = 255;

const int UINT_FAST16_MAX = 65535;

const int UINT_FAST32_MAX = 4294967295;

const int UINT_FAST64_MAX = -1;

const int INTPTR_MAX = 9223372036854775807;

const int INTPTR_MIN = -9223372036854775808;

const int UINTPTR_MAX = -1;

const int INTMAX_MAX = 9223372036854775807;

const int UINTMAX_MAX = -1;

const int INTMAX_MIN = -9223372036854775808;

const int PTRDIFF_MIN = -9223372036854775808;

const int PTRDIFF_MAX = 9223372036854775807;

const int SIZE_MAX = -1;

const int RSIZE_MAX = 9223372036854775807;

const int WCHAR_MAX = 2147483647;

const int WCHAR_MIN = -2147483648;

const int WINT_MIN = -2147483648;

const int WINT_MAX = 2147483647;

const int SIG_ATOMIC_MIN = -2147483648;

const int SIG_ATOMIC_MAX = 2147483647;

typedef _c_rune_error_new = ffi.Pointer<Error> Function(
  ffi.Pointer<ffi.Int8> msg,
);

typedef _dart_rune_error_new = ffi.Pointer<Error> Function(
  ffi.Pointer<ffi.Int8> msg,
);

typedef _c_rune_error_free = ffi.Void Function(
  ffi.Pointer<Error> e,
);

typedef _dart_rune_error_free = void Function(
  ffi.Pointer<Error> e,
);

typedef _c_rune_error_backtrace = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<Error> error,
);

typedef _dart_rune_error_backtrace = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<Error> error,
);

typedef _c_rune_error_to_string = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<Error> error,
);

typedef _dart_rune_error_to_string = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<Error> error,
);

typedef _c_rune_error_to_string_verbose = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<Error> error,
);

typedef _dart_rune_error_to_string_verbose = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<Error> error,
);

typedef _c_rune_wasmer_runtime_free = ffi.Void Function(
  ffi.Pointer<WasmerRuntime> runtime,
);

typedef _dart_rune_wasmer_runtime_free = void Function(
  ffi.Pointer<WasmerRuntime> runtime,
);

typedef _c_rune_image_new = ffi.Pointer<RunicosBaseImage> Function();

typedef _dart_rune_image_new = ffi.Pointer<RunicosBaseImage> Function();

typedef _c_rune_image_free = ffi.Void Function(
  ffi.Pointer<RunicosBaseImage> image,
);

typedef _dart_rune_image_free = void Function(
  ffi.Pointer<RunicosBaseImage> image,
);

typedef _typedefC_1 = ffi.Void Function(
  ffi.Pointer<ffi.Void>,
);

typedef _typedefC_2 = ffi.Int32 Function(
  ffi.Pointer<ffi.Void>,
  LogRecord_t,
);

typedef _typedefC_3 = ffi.Void Function(
  ffi.Pointer<ffi.Void>,
);
